- name: "Communication"
  type: "wg"
  role: "CS representative"
  descr: "WG on institutional communication policies"

- name: "CS PhD regulations"
  type: "wg"
  role: "Chair"
  descr: "WG on PhD regulations of the CS area"

- name: "visiting regulation"
  type: "wg"
  role: "Reviewer"
  descr: "visiting regulations"

- name: "seminars"
  type: "wg"
  role: "Organiser"
  descr: "serminars of the CS area"

- name: "a post-doc on the DeLiCE project"
  type: "hire"
  institution: "University of Cagliari (Italy)"
  role: "Member"
  date: "13/3/2024"

- name: "a post-doc on the DeLiCE project"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Chair"
  date: "5/3/2013"

- name: "a post-doc on the DREAM project"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Chair"
  date: "4/3/2013"

- name: "an RTDa position"
  type: "hire"
  institution: "University of Turin, Italy"
  role: "Chair"
  date: "13/7/2023"

- name: "a post-doc on the CUIM project"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Chair"
  date: "9/9/2021"

- name: "a post-doc on the IT-Matters project"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Member"
  date: "7/4/2021"

- name: "2 post-docs"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Member"
  date: "27/7/2020"

- name: "PhD admission (XXXVI cicle)"
  type: "hire"
  institution: "University of Camerino (Italy)"
  role: "Member"
  date: "7-9/9/2020"

- name: "PhD admission (XXXV cicle)"
  type: "hire"
  institution: "Gran Sasso Science Institute (L'Aquila, Italy)"
  role: "Member"
  date: "5/7/2019"

- name: "Italian PhD program"
  type: "collegio"
  institution: "GSSI"
  role: "Member"
  date: "2022-2023"

- name: "Italian PhD program"
  type: "collegio"
  institution: "Scuola di interesse nazionale in cybersecurity of the IMT Alti Studi - Lucca"
  role: "Member"
  date: "2022-2023"

- name: "Italian PhD program"
  type: "collegio"
  institution: "GSSI"
  role: "Member"
  date: "2021-2022"
